# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
      - dependencies
    authors:
      - dependabot[bot]
      - github-actions[bot]
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
        - major
    - title: Exciting New Features 🎉
      labels:
        - enhancement
        - feature
        - new-feature
    - title: Bug Fixes 🐛
      labels:
        - bug
        - bugfix
        - fix
    - title: Performance Improvements 🚀
      labels:
        - performance
        - optimization
    - title: Documentation 📝
      labels:
        - documentation
        - docs
    - title: Configuration Changes 🔧
      labels:
        - config
        - configuration
        - ci
    - title: Code Style & Refactoring 🎨
      labels:
        - style
        - refactor
        - cleanup
    - title: Dependencies 📦
      labels:
        - dependencies
        - deps
    - title: Other Changes
      labels:
        - "*"