[package]
edition = "2021"
name = "claude-code-extension"
version = "0.1.4"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true, features = ["js"] }
zed_extension_api = "0.6.0"
