name: Build and Release Claude Code Server

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            name: claude-code-server-linux-x86_64
          - target: x86_64-apple-darwin
            os: macos-latest
            name: claude-code-server-macos-x86_64
          - target: aarch64-apple-darwin
            os: macos-latest
            name: claude-code-server-macos-aarch64
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            name: claude-code-server-windows-x86_64.exe

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
    
    - name: Build binary
      run: |
        cd claude-code-server
        cargo build --release --target ${{ matrix.target }}
    
    - name: Prepare artifact (Unix)
      if: matrix.os != 'windows-latest'
      run: |
        cp claude-code-server/target/${{ matrix.target }}/release/claude-code-server ${{ matrix.name }}
        chmod +x ${{ matrix.name }}
    
    - name: Prepare artifact (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        cp claude-code-server/target/${{ matrix.target }}/release/claude-code-server.exe ${{ matrix.name }}
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.name }}
        path: ${{ matrix.name }}

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          claude-code-server-linux-x86_64/claude-code-server-linux-x86_64
          claude-code-server-macos-x86_64/claude-code-server-macos-x86_64
          claude-code-server-macos-aarch64/claude-code-server-macos-aarch64
          claude-code-server-windows-x86_64.exe/claude-code-server-windows-x86_64.exe
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}